/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthDebugRouteImport } from './routes/auth-debug'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated/sos'
import { Route as AuthenticatedRoleSelectRouteImport } from './routes/_authenticated/role-select'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrivacySecurityRouteImport } from './routes/_authenticated/privacy-security'
import { Route as AuthenticatedPersonalInformationRouteImport } from './routes/_authenticated/personal-information'
import { Route as AuthenticatedNotificationSettingsRouteImport } from './routes/_authenticated/notification-settings'
import { Route as AuthenticatedLanguageSelectionRouteImport } from './routes/_authenticated/language-selection'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAlertsHistoryRouteImport } from './routes/_authenticated/alerts-history'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDebugRoute = AuthDebugRouteImport.update({
  id: '/auth-debug',
  path: '/auth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoleSelectRoute = AuthenticatedRoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacySecurityRoute =
  AuthenticatedPrivacySecurityRouteImport.update({
    id: '/privacy-security',
    path: '/privacy-security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonalInformationRoute =
  AuthenticatedPersonalInformationRouteImport.update({
    id: '/personal-information',
    path: '/personal-information',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationSettingsRoute =
  AuthenticatedNotificationSettingsRouteImport.update({
    id: '/notification-settings',
    path: '/notification-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLanguageSelectionRoute =
  AuthenticatedLanguageSelectionRouteImport.update({
    id: '/language-selection',
    path: '/language-selection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsHistoryRoute =
  AuthenticatedAlertsHistoryRouteImport.update({
    id: '/alerts-history',
    path: '/alerts-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/auth-debug': typeof AuthDebugRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AuthenticatedAiRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/alerts-history': typeof AuthenticatedAlertsHistoryRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/language-selection': typeof AuthenticatedLanguageSelectionRoute
  '/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/personal-information': typeof AuthenticatedPersonalInformationRoute
  '/privacy-security': typeof AuthenticatedPrivacySecurityRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/role-select': typeof AuthenticatedRoleSelectRoute
  '/sos': typeof AuthenticatedSosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/auth-debug': typeof AuthDebugRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AuthenticatedAiRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/alerts-history': typeof AuthenticatedAlertsHistoryRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/language-selection': typeof AuthenticatedLanguageSelectionRoute
  '/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/personal-information': typeof AuthenticatedPersonalInformationRoute
  '/privacy-security': typeof AuthenticatedPrivacySecurityRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/role-select': typeof AuthenticatedRoleSelectRoute
  '/sos': typeof AuthenticatedSosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/auth-debug': typeof AuthDebugRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/alerts-history': typeof AuthenticatedAlertsHistoryRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/language-selection': typeof AuthenticatedLanguageSelectionRoute
  '/_authenticated/notification-settings': typeof AuthenticatedNotificationSettingsRoute
  '/_authenticated/personal-information': typeof AuthenticatedPersonalInformationRoute
  '/_authenticated/privacy-security': typeof AuthenticatedPrivacySecurityRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/role-select': typeof AuthenticatedRoleSelectRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/auth-debug'
    | '/reset-password'
    | '/sitemap.xml'
    | '/ai'
    | '/alerts'
    | '/alerts-history'
    | '/change-password'
    | '/dashboard'
    | '/language-selection'
    | '/notification-settings'
    | '/personal-information'
    | '/privacy-security'
    | '/profile'
    | '/report'
    | '/role-select'
    | '/sos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/auth-debug'
    | '/reset-password'
    | '/sitemap.xml'
    | '/ai'
    | '/alerts'
    | '/alerts-history'
    | '/change-password'
    | '/dashboard'
    | '/language-selection'
    | '/notification-settings'
    | '/personal-information'
    | '/privacy-security'
    | '/profile'
    | '/report'
    | '/role-select'
    | '/sos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/auth-debug'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/ai'
    | '/_authenticated/alerts'
    | '/_authenticated/alerts-history'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/language-selection'
    | '/_authenticated/notification-settings'
    | '/_authenticated/personal-information'
    | '/_authenticated/privacy-security'
    | '/_authenticated/profile'
    | '/_authenticated/report'
    | '/_authenticated/role-select'
    | '/_authenticated/sos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthDebugRoute: typeof AuthDebugRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-debug': {
      id: '/auth-debug'
      path: '/auth-debug'
      fullPath: '/auth-debug'
      preLoaderRoute: typeof AuthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role-select': {
      id: '/_authenticated/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof AuthenticatedRoleSelectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy-security': {
      id: '/_authenticated/privacy-security'
      path: '/privacy-security'
      fullPath: '/privacy-security'
      preLoaderRoute: typeof AuthenticatedPrivacySecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personal-information': {
      id: '/_authenticated/personal-information'
      path: '/personal-information'
      fullPath: '/personal-information'
      preLoaderRoute: typeof AuthenticatedPersonalInformationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-settings': {
      id: '/_authenticated/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof AuthenticatedNotificationSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/language-selection': {
      id: '/_authenticated/language-selection'
      path: '/language-selection'
      fullPath: '/language-selection'
      preLoaderRoute: typeof AuthenticatedLanguageSelectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts-history': {
      id: '/_authenticated/alerts-history'
      path: '/alerts-history'
      fullPath: '/alerts-history'
      preLoaderRoute: typeof AuthenticatedAlertsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAlertsHistoryRoute: typeof AuthenticatedAlertsHistoryRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLanguageSelectionRoute: typeof AuthenticatedLanguageSelectionRoute
  AuthenticatedNotificationSettingsRoute: typeof AuthenticatedNotificationSettingsRoute
  AuthenticatedPersonalInformationRoute: typeof AuthenticatedPersonalInformationRoute
  AuthenticatedPrivacySecurityRoute: typeof AuthenticatedPrivacySecurityRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedRoleSelectRoute: typeof AuthenticatedRoleSelectRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAlertsHistoryRoute: AuthenticatedAlertsHistoryRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLanguageSelectionRoute: AuthenticatedLanguageSelectionRoute,
  AuthenticatedNotificationSettingsRoute:
    AuthenticatedNotificationSettingsRoute,
  AuthenticatedPersonalInformationRoute: AuthenticatedPersonalInformationRoute,
  AuthenticatedPrivacySecurityRoute: AuthenticatedPrivacySecurityRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedRoleSelectRoute: AuthenticatedRoleSelectRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthDebugRoute: AuthDebugRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
